export type SubtaskCategory = {
  id: string;
  name: string;
  shortName: string;
  icon: string;
  description: string;
  color: string;
};

export type CuratedSubtask = {
  id: string;
  title: string;
  categoryId: string;
  categoryName: string;
  status: "pending" | "completed";
  weight: string; // e.g. "High Yield · 4-6 Marks" | "Core Fundamental" | "Scoring Topic"
  resource: {
    title: string;
    type: "youtube" | "notes" | "practice";
    creator: string;
    url: string;
    badge: string;
  };
};

export const GATE_CATEGORIES: SubtaskCategory[] = [
  {
    id: "os",
    name: "Operating Systems",
    shortName: "OS",
    icon: "💻",
    description: "Processes, Threads, CPU Scheduling, Deadlocks, Memory Management, Paging, Virtual Memory & File Systems",
    color: "#38bdf8",
  },
  {
    id: "dbms",
    name: "Databases (DBMS)",
    shortName: "DBMS",
    icon: "🗄️",
    description: "ER Model, Relational Algebra, SQL, Normalization (1NF–BCNF), Transactions, ACID & Concurrency Control",
    color: "#a855f7",
  },
  {
    id: "cn",
    name: "Computer Networks",
    shortName: "Networks",
    icon: "🌐",
    description: "OSI & TCP/IP, Framing, Error Control, Subnetting (CIDR), Routing Protocols, TCP Flow & Congestion Control",
    color: "#3b82f6",
  },
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    shortName: "DSA",
    icon: "⚡",
    description: "Asymptotic Analysis, Trees, AVL Trees, Heaps, Graphs, Sorting, Greedy, Dynamic Programming & Divide/Conquer",
    color: "#10b981",
  },
  {
    id: "toc",
    name: "Theory of Computation",
    shortName: "TOC",
    icon: "⚙️",
    description: "DFA, NFA, Regular Expressions, Context-Free Grammars, Pushdown Automata, Turing Machines & Decidability",
    color: "#f59e0b",
  },
  {
    id: "compiler",
    name: "Compiler Design",
    shortName: "Compilers",
    icon: "🛠️",
    description: "Lexical Analysis, Top-Down LL(1) Parsing, Bottom-Up LR Parsing, SDT, Intermediate Code & Optimization",
    color: "#ec4899",
  },
  {
    id: "em",
    name: "Engineering Mathematics",
    shortName: "Engg Maths",
    icon: "📐",
    description: "Linear Algebra, Matrices, Eigenvalues, Calculus, Maxima/Minima, Probability & Distributions",
    color: "#6366f1",
  },
  {
    id: "dm",
    name: "Discrete Mathematics",
    shortName: "Discrete Maths",
    icon: "🧩",
    description: "Propositional Logic, Predicates, Set Theory, Relations, Combinatorics, Graph Theory & Group Theory",
    color: "#14b8a6",
  },
  {
    id: "coa",
    name: "Digital Logic & Computer Org",
    shortName: "COA & Digital",
    icon: "🔌",
    description: "K-Maps, Combinational & Sequential Circuits, Pipelining, Cache Memory Mapping & Instruction Addressing",
    color: "#f97316",
  },
  {
    id: "mocks",
    name: "General Aptitude & PYQs",
    shortName: "Aptitude & PYQs",
    icon: "📝",
    description: "Numerical Ability, Verbal Reasoning, 10-Year Solved GATE Papers, Timed Mock Simulations",
    color: "#84cc16",
  },
];

export const GATE_100_SUBTASKS: CuratedSubtask[] = [

  // ── 1. OPERATING SYSTEMS (12 Subtasks) ──────────────────────────
  {
    id: "gate-os-1",
    title: "Process Concepts, Process States & Process Control Block (PCB)",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Process States and PCB Explained",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=gate+smashers+process+states+pcb",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-os-2",
    title: "CPU Scheduling: FCFS, SJF & Shortest Remaining Time First (SRTF)",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "CPU Scheduling Algorithms Masterclass",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=cpu+scheduling+algorithms+gate+sjf+srtf",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-os-3",
    title: "Round Robin Scheduling & Priority-Based Scheduling Calculations",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Numerical · 2 Marks",
    resource: {
      title: "Round Robin Gantt Chart & Time Quantum Analysis",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=round+robin+scheduling+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-os-4",
    title: "Critical Section Problem & Peterson's Mutual Exclusion Algorithm",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Core Theory · 2 Marks",
    resource: {
      title: "Critical Section and Peterson's Solution",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=petersons+algorithm+critical+section+abdul+bari",
      badge: "Concept Lecture",
    },
  },
  {
    id: "gate-os-5",
    title: "Counting & Binary Semaphores with Classical Synchronization Problems",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Semaphores & Producer Consumer Problem in OS",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=semaphores+producer+consumer+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-os-6",
    title: "Deadlock Conditions, Resource Allocation Graphs (RAG) & Prevention",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Deadlock Necessary Conditions & Resource Allocation Graph",
      type: "youtube",
      creator: "NPTEL CS",
      url: "https://www.youtube.com/results?search_query=deadlock+conditions+resource+allocation+graph+gate",
      badge: "NPTEL / Video",
    },
  },
  {
    id: "gate-os-7",
    title: "Banker's Algorithm for Deadlock Avoidance with Safety Algorithm",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "Banker's Algorithm Solved Examples for GATE",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=bankers+algorithm+gate+smashers",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-os-8",
    title: "Contiguous Memory Allocation, Internal & External Fragmentation",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Fragmentation in OS Memory Management",
      type: "youtube",
      creator: "Jenny's Lectures",
      url: "https://www.youtube.com/results?search_query=fragmentation+memory+management+jennys+lectures",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-os-9",
    title: "Paging Architecture, Page Table Size & Multi-Level Paging Calculations",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Multi-Level Paging Numerical Formulas & Solved GATE Questions",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=paging+page+table+size+multilevel+gate+smashers",
      badge: "High Yield Video",
    },
  },
  {
    id: "gate-os-10",
    title: "Translation Lookaside Buffer (TLB) Hit Ratio & Effective Memory Access Time (EMAT)",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "TLB Effective Memory Access Time EMAT Problems",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=tlb+effective+memory+access+time+emat+gate",
      badge: "Numerical Guide",
    },
  },
  {
    id: "gate-os-11",
    title: "Page Replacement Algorithms: FIFO, LRU, Optimal & Belady's Anomaly",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Frequent Question · 2 Marks",
    resource: {
      title: "Page Replacement Algorithms FIFO LRU Optimal",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=page+replacement+algorithms+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-os-12",
    title: "Disk Scheduling: FCFS, SSTF, SCAN, C-SCAN, LOOK & C-LOOK",
    categoryId: "os",
    categoryName: "Operating Systems",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Disk Scheduling Algorithms Solved Problems",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=disk+scheduling+algorithms+gate+smashers",
      badge: "Video Tutorial",
    },
  },

  // ── 2. DATABASES (DBMS) (11 Subtasks) ──────────────────────────
  {
    id: "gate-dbms-1",
    title: "Entity-Relationship (ER) Model, Weak Entities & Min/Max Cardinalities",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "ER Model & ER to Relational Mapping",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=er+model+relational+mapping+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-dbms-2",
    title: "Relational Algebra: Selection, Projection, Cartesian Product & Joins",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Relational Algebra Operators and Queries for GATE",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=relational+algebra+gate+queries",
      badge: "Concept Video",
    },
  },
  {
    id: "gate-dbms-3",
    title: "Relational Algebra: Set Difference, Intersection & Division Operator",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Advanced Theory · 2 Marks",
    resource: {
      title: "Division Operator in Relational Algebra Solved Examples",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=division+operator+relational+algebra+gate+smashers",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-dbms-4",
    title: "Tuple Relational Calculus (TRC) & Domain Relational Calculus (DRC)",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "Tuple & Domain Relational Calculus Explained",
      type: "youtube",
      creator: "Amit Khurana",
      url: "https://www.youtube.com/results?search_query=tuple+relational+calculus+trc+drc+gate",
      badge: "Theory Guide",
    },
  },
  {
    id: "gate-dbms-5",
    title: "SQL Queries: Group By, Having, Nested Subqueries & Correlated Queries",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "SQL Nested and Correlated Queries Solved for GATE",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=sql+nested+queries+gate+smashers",
      badge: "Hands-on Video",
    },
  },
  {
    id: "gate-dbms-6",
    title: "Functional Dependencies, Attribute Closure & Finding Candidate Keys",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "How to Find Candidate Keys from Functional Dependencies",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=candidate+keys+functional+dependencies+gate+smashers",
      badge: "Shortcut Method",
    },
  },
  {
    id: "gate-dbms-7",
    title: "Canonical Cover (Minimal Cover) of Functional Dependencies",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Numerical · 2 Marks",
    resource: {
      title: "Minimal Cover Algorithm Step by Step",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=minimal+cover+canonical+cover+dbms+gate",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dbms-8",
    title: "Normalization: 1NF, 2NF, 3NF, BCNF & Checking Normal Form of Relations",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Normalization Masterclass 1NF 2NF 3NF BCNF",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=normalization+1nf+2nf+3nf+bcnf+gate+smashers",
      badge: "Comprehensive",
    },
  },
  {
    id: "gate-dbms-9",
    title: "Lossless Join Decomposition & Dependency Preservation Verification",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Frequent Question · 2 Marks",
    resource: {
      title: "Testing Lossless Join & Dependency Preservation",
      type: "youtube",
      creator: "Amit Khurana",
      url: "https://www.youtube.com/results?search_query=lossless+join+decomposition+dependency+preservation+gate",
      badge: "Method & Proof",
    },
  },
  {
    id: "gate-dbms-10",
    title: "Transaction ACID Properties & Conflict Serializability Testing (Precedence Graph)",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Conflict Serializability and Precedence Graph Testing",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=conflict+serializability+precedence+graph+gate+smashers",
      badge: "Solved Problems",
    },
  },
  {
    id: "gate-dbms-11",
    title: "B-Trees and B+ Trees: Order, Maximum/Minimum Keys, Depth & Index Calculations",
    categoryId: "dbms",
    categoryName: "Databases (DBMS)",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "B Tree and B+ Tree Numerical Calculations for GATE",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=b+tree+b+plus+tree+numerical+gate+smashers",
      badge: "High Yield Video",
    },
  },

  // ── 3. COMPUTER NETWORKS (11 Subtasks) ──────────────────────────
  {
    id: "gate-cn-1",
    title: "OSI Reference Model vs TCP/IP Layering & Header Overhead Analysis",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "OSI Model vs TCP IP Protocol Architecture",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=osi+model+layers+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-cn-2",
    title: "Framing & Flow Control: Stop-and-Wait Protocol & Efficiency Calculation",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "Stop and Wait Efficiency and Bandwidth Delay Product",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=stop+and+wait+protocol+efficiency+gate+smashers",
      badge: "Formula & Problems",
    },
  },
  {
    id: "gate-cn-3",
    title: "Sliding Window Protocols: Go-Back-N (GBN) vs Selective Repeat (SR)",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Go Back N vs Selective Repeat Window Size & Efficiency",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=go+back+n+selective+repeat+gate",
      badge: "Detailed Tutorial",
    },
  },
  {
    id: "gate-cn-4",
    title: "Error Detection: CRC (Cyclic Redundancy Check) Polynomial Division",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Numerical · 2 Marks",
    resource: {
      title: "Cyclic Redundancy Check CRC Calculation Solved Example",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=crc+error+detection+gate+smashers",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-cn-5",
    title: "Medium Access Control: Pure ALOHA, Slotted ALOHA & CSMA/CD Minimum Frame Size",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "CSMA/CD Minimum Frame Size and Efficiency Formulas",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=csma+cd+minimum+frame+size+efficiency+gate+smashers",
      badge: "High Yield Video",
    },
  },
  {
    id: "gate-cn-6",
    title: "IPv4 Addressing, Subnet Masking, CIDR & Subnetting Calculations",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Subnetting and CIDR Address Allocation for GATE",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=subnetting+cidr+ip+addressing+gate+smashers",
      badge: "Essential Video",
    },
  },
  {
    id: "gate-cn-7",
    title: "IPv4 Header Format, MTU & Packet Fragmentation Calculations",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "IP Fragmentation Offset and Header Fields Solved Questions",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=ip+fragmentation+offset+gate+questions",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-cn-8",
    title: "Routing Algorithms: Distance Vector (Bellman-Ford) & Count-to-Infinity Problem",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Core Theory · 2 Marks",
    resource: {
      title: "Distance Vector Routing and Count to Infinity",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=distance+vector+routing+count+to+infinity+gate+smashers",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-cn-9",
    title: "Link State Routing (Dijkstra) & Hierarchical Routing",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "Link State Routing and OSPF Protocol Fundamentals",
      type: "youtube",
      creator: "NPTEL CS",
      url: "https://www.youtube.com/results?search_query=link+state+routing+gate+smashers",
      badge: "Video Guide",
    },
  },
  {
    id: "gate-cn-10",
    title: "TCP 3-Way Handshake, Connection Teardown & Header Flags",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "Core Theory · 2 Marks",
    resource: {
      title: "TCP 3 Way Handshake & Connection Termination Detailed",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=tcp+3+way+handshake+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-cn-11",
    title: "TCP Congestion Control: Slow Start, Congestion Avoidance, Fast Retransmit & AIMD",
    categoryId: "cn",
    categoryName: "Computer Networks",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "TCP Congestion Window Dynamics Solved Problems for GATE",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=tcp+congestion+control+slow+start+gate",
      badge: "High Yield Video",
    },
  },

  // ── 4. DATA STRUCTURES & ALGORITHMS (15 Subtasks) ─────────────
  {
    id: "gate-dsa-1",
    title: "Asymptotic Notations (Big-O, Omega, Theta, Little-o) & Rate of Growth",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Asymptotic Notation and Growth of Functions",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=asymptotic+notation+abdul+bari",
      badge: "Classic Lecture",
    },
  },
  {
    id: "gate-dsa-2",
    title: "Recurrence Relations: Master Theorem & Substitution Method",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Master Theorem for Divide and Conquer Recurrences",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=master+theorem+abdul+bari",
      badge: "Top Tutorial",
    },
  },
  {
    id: "gate-dsa-3",
    title: "Row-Major and Column-Major Address Calculations in Multi-dimensional Arrays",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Numerical · 2 Marks",
    resource: {
      title: "Row Major and Column Major Array Address Formulas",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=row+major+column+major+array+address+gate",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-dsa-4",
    title: "Linked Lists: Insertion, Deletion, Reversal, Cycle Detection & Skip Lists",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Linked List Reversal and Cycle Finding Techniques",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=linked+list+abdul+bari",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dsa-5",
    title: "Stacks: Infix to Postfix/Prefix Conversion & Postfix Evaluation",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Infix to Postfix Conversion Using Stack Algorithm",
      type: "youtube",
      creator: "Jenny's Lectures",
      url: "https://www.youtube.com/results?search_query=infix+to+postfix+conversion+stack+jennys+lectures",
      badge: "Video Guide",
    },
  },
  {
    id: "gate-dsa-6",
    title: "Queues: Circular Queue Array Implementation & Two-Stack Queue",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Circular Queue Implementation and Overflow/Underflow",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=circular+queue+abdul+bari",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-dsa-7",
    title: "Binary Trees: Preorder, Inorder, Postorder & Reconstructing Tree from Traversals",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Construct Tree from Inorder and Preorder Traversals",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=construct+binary+tree+traversals+abdul+bari",
      badge: "Masterclass",
    },
  },
  {
    id: "gate-dsa-8",
    title: "Binary Search Trees (BST): Insertion, Deletion & Finding Inorder Predecessor/Successor",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "BST Deletion with 3 Cases & Number of BSTs Formula",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=binary+search+tree+bst+abdul+bari",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-dsa-9",
    title: "AVL Trees: Balance Factor, Rotations (LL, RR, LR, RL) & Height vs Nodes Bounds",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "AVL Tree Rotations and Insertion Explained Simply",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=avl+trees+rotations+abdul+bari",
      badge: "Essential Video",
    },
  },
  {
    id: "gate-dsa-10",
    title: "Binary Heaps & Heap Sort: Min Heap, Max Heap, Heapify in O(n) & Priority Queues",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Frequent Question · 3 Marks",
    resource: {
      title: "Heapify and Heap Sort Algorithm Breakdown",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=heap+sort+heapify+abdul+bari",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dsa-11",
    title: "Hashing: Separate Chaining, Open Addressing (Linear, Quadratic, Double Hashing)",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Hashing Collision Resolution Techniques Solved Questions",
      type: "youtube",
      creator: "Jenny's Lectures",
      url: "https://www.youtube.com/results?search_query=hashing+collision+resolution+jennys+lectures",
      badge: "Concept Guide",
    },
  },
  {
    id: "gate-dsa-12",
    title: "Sorting Algorithms Comparison: Quicksort, Mergesort, Heapsort & Stability",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "Comparative · 2 Marks",
    resource: {
      title: "Sorting Algorithms Time Space Complexity & Stability",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=sorting+algorithms+comparison+abdul+bari",
      badge: "Summary Chart",
    },
  },
  {
    id: "gate-dsa-13",
    title: "Graph Traversals: BFS, DFS, Connected Components, Bipartite & Topological Sort",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "BFS, DFS and Topological Sort using DFS",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=bfs+dfs+topological+sort+abdul+bari",
      badge: "Masterclass",
    },
  },
  {
    id: "gate-dsa-14",
    title: "Greedy Algorithms: Huffman Coding, Fractional Knapsack, Activity Selection",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Huffman Coding Algorithm & Compression Ratio",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=huffman+coding+abdul+bari",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-dsa-15",
    title: "Dynamic Programming: 0/1 Knapsack, Longest Common Subsequence (LCS) & Matrix Chain",
    categoryId: "dsa",
    categoryName: "Data Structures & Algorithms",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Dynamic Programming: 0/1 Knapsack & LCS Table Construction",
      type: "youtube",
      creator: "Abdul Bari",
      url: "https://www.youtube.com/results?search_query=dynamic+programming+knapsack+lcs+abdul+bari",
      badge: "Top DP Lecture",
    },
  },

  // ── 5. THEORY OF COMPUTATION (11 Subtasks) ─────────────────────
  {
    id: "gate-toc-1",
    title: "Deterministic Finite Automata (DFA): Design, Traps & State Transitions",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "DFA Construction Problems with Shortcuts",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=dfa+construction+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-toc-2",
    title: "DFA Minimization: Myhill-Nerode Theorem & Table-Filling Algorithm",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Minimization of DFA Table Filling Method Step by Step",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=minimization+of+dfa+table+filling+method+gate",
      badge: "Algorithm Video",
    },
  },
  {
    id: "gate-toc-3",
    title: "Nondeterministic Finite Automata (NFA) to DFA Subset Construction",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "NFA to DFA Conversion Subset Construction",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=nfa+to+dfa+conversion+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-toc-4",
    title: "Regular Expressions, Arden's Theorem & Equivalence with Finite Automata",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Frequent Question · 2 Marks",
    resource: {
      title: "Arden's Theorem for Finding Regular Expression from DFA",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=ardens+theorem+regular+expression+gate+smashers",
      badge: "Formula & Proof",
    },
  },
  {
    id: "gate-toc-5",
    title: "Pumping Lemma for Regular Languages & Proving Non-Regularity",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "Pumping Lemma for Regular Languages Explained with Counter-Examples",
      type: "youtube",
      creator: "Amit Khurana",
      url: "https://www.youtube.com/results?search_query=pumping+lemma+for+regular+languages+gate",
      badge: "Theory Lecture",
    },
  },
  {
    id: "gate-toc-6",
    title: "Context-Free Grammars (CFG), Ambiguity & Derivation Trees",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Ambiguous Grammar and Leftmost/Rightmost Derivation",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=ambiguous+grammar+derivation+trees+gate+smashers",
      badge: "Video Guide",
    },
  },
  {
    id: "gate-toc-7",
    title: "Pushdown Automata (PDA): Acceptance by Empty Stack vs Final State & DPDA",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Pushdown Automata PDA Construction for Palindromes and anbn",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=pushdown+automata+pda+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-toc-8",
    title: "Chomsky Hierarchy of Languages: Type 0, Type 1, Type 2, Type 3 Grammar Relations",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Chomsky Hierarchy Classification Table",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=chomsky+hierarchy+gate+cs",
      badge: "Comparison Chart",
    },
  },
  {
    id: "gate-toc-9",
    title: "Closure Properties of Regular, CFL, DCFL, CSL, Recursive & RE Languages",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Language Closure Properties Master Table with Tricks",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=closure+properties+of+languages+gate+smashers",
      badge: "High Yield Trick",
    },
  },
  {
    id: "gate-toc-10",
    title: "Turing Machines: Standard, Multi-Tape, Non-Deterministic TM & Universal TM",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "Turing Machine Architecture and Instantaneous Description",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=turing+machine+gate+smashers",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-toc-11",
    title: "Decidability, Undecidability, Halting Problem & Post Correspondence Problem (PCP)",
    categoryId: "toc",
    categoryName: "Theory of Computation",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Decidability Table & Halting Problem Master Summary",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=decidability+undecidability+halting+problem+gate+smashers",
      badge: "Essential Table",
    },
  },

  // ── 6. COMPILER DESIGN (9 Subtasks) ────────────────────────────
  {
    id: "gate-cd-1",
    title: "Compiler Phases, Pass Structure, Symbol Table & Lexical Tokens",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Phases of a Compiler Overview",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=phases+of+compiler+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-cd-2",
    title: "Computation of FIRST & FOLLOW Sets for Context-Free Grammars",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "How to Find FIRST and FOLLOW Sets with Zero Errors",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=first+and+follow+in+compiler+gate+smashers",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-cd-3",
    title: "LL(1) Predictive Parsing Table Construction & Checking LL(1) Eligibility",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "LL1 Parser Table Construction and Conflicts",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=ll1+parsing+table+construction+gate",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-cd-4",
    title: "Shift-Reduce Parsing, Handle Pruning & Shift-Reduce / Reduce-Reduce Conflicts",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Shift Reduce Parsing and Parser Conflicts",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=shift+reduce+parsing+conflicts+gate+smashers",
      badge: "Concept Guide",
    },
  },
  {
    id: "gate-cd-5",
    title: "LR(0) and SLR(1) Parsing Table Construction & Canonical Collection of Items",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "LR0 and SLR1 Items and Parser Table",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=lr0+slr1+parsing+table+gate+smashers",
      badge: "Video Masterclass",
    },
  },
  {
    id: "gate-cd-6",
    title: "CLR(1) and LALR(1) Parsing Tables & Merging Common Core States",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "CLR1 vs LALR1 Parsers Differences and Merging States",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=clr1+lalr1+parsing+table+gate",
      badge: "Comparison Video",
    },
  },
  {
    id: "gate-cd-7",
    title: "Syntax-Directed Translation (SDT): S-Attributed vs L-Attributed Definitions",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "S Attributed vs L Attributed SDT Evaluation Order",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=s+attributed+l+attributed+sdt+gate+smashers",
      badge: "Core Theory",
    },
  },
  {
    id: "gate-cd-8",
    title: "Intermediate Code Generation: Three-Address Code, Quadruples & Triples",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Three Address Code Quadruples Triples Indirect Triples",
      type: "youtube",
      creator: "Jenny's Lectures",
      url: "https://www.youtube.com/results?search_query=three+address+code+quadruples+triples+jennys+lectures",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-cd-9",
    title: "Code Optimization: Basic Blocks, Flow Graphs, Common Subexpressions & Loop Invariants",
    categoryId: "compiler",
    categoryName: "Compiler Design",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Basic Blocks and Flow Graphs Code Optimization Techniques",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=basic+blocks+flow+graphs+code+optimization+gate+smashers",
      badge: "Optimization Guide",
    },
  },

  // ── 7. ENGINEERING MATHEMATICS (10 Subtasks) ───────────────────
  {
    id: "gate-em-1",
    title: "Matrices, Determinants & System of Linear Equations (Ax = B Consistency)",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "System of Linear Equations Consistency Conditions",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=system+of+linear+equations+consistency+gajendra+purohit",
      badge: "Math Masterclass",
    },
  },
  {
    id: "gate-em-2",
    title: "Rank of Matrix, Nullity & Rank-Nullity Theorem",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Rank of Matrix and Rank Nullity Theorem",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=rank+of+matrix+gajendra+purohit",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-em-3",
    title: "Eigenvalues, Eigenvectors & Cayley-Hamilton Theorem Applications",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Eigenvalues and Eigenvectors Properties and Shortcuts",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=eigenvalues+eigenvectors+properties+shortcuts+gate",
      badge: "Top Math Video",
    },
  },
  {
    id: "gate-em-4",
    title: "Limits, Continuity, Differentiability & L'Hôpital's Rule Applications",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Limits and L'Hospital's Rule Indeterminate Forms",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=limits+l+hopital+rule+gajendra+purohit",
      badge: "Video Lecture",
    },
  },
  {
    id: "gate-em-5",
    title: "Mean Value Theorems: Rolle's, Lagrange's & Cauchy's Mean Value Theorem",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "Theory · 2 Marks",
    resource: {
      title: "Rolle's Theorem & Lagrange's Mean Value Theorem",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=mean+value+theorems+gajendra+purohit",
      badge: "Video Guide",
    },
  },
  {
    id: "gate-em-6",
    title: "Maxima, Minima & Saddle Points for Functions of Single and Two Variables",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "Maxima and Minima of Two Variable Functions Saddle Point",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=maxima+minima+two+variables+gajendra+purohit",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-em-7",
    title: "Conditional Probability, Total Probability & Bayes' Theorem Applications",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Bayes Theorem and Conditional Probability GATE Solved Questions",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=bayes+theorem+probability+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-em-8",
    title: "Discrete Distributions: Uniform, Bernoulli, Binomial & Poisson Distributions",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Binomial and Poisson Distribution Formulas and Expectation",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=binomial+poisson+distribution+gajendra+purohit",
      badge: "Math Lecture",
    },
  },
  {
    id: "gate-em-9",
    title: "Continuous Distributions: Exponential & Normal (Gaussian) Distribution",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Exponential and Normal Distribution Standard Normal Curve",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=normal+distribution+exponential+gajendra+purohit",
      badge: "Video Guide",
    },
  },
  {
    id: "gate-em-10",
    title: "Descriptive Statistics: Mean, Median, Mode, Variance, Covariance & Standard Deviation",
    categoryId: "em",
    categoryName: "Engineering Mathematics",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Mean Median Mode Variance Covariance Formulas",
      type: "youtube",
      creator: "Gajendra Purohit",
      url: "https://www.youtube.com/results?search_query=variance+covariance+standard+deviation+gajendra+purohit",
      badge: "Summary Video",
    },
  },

  // ── 8. DISCRETE MATHEMATICS (10 Subtasks) ──────────────────────
  {
    id: "gate-dm-1",
    title: "Propositional Logic: Truth Tables, Tautology, Contradiction & Logical Equivalences",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Propositional Logic Connectives and Truth Tables",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=propositional+logic+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-dm-2",
    title: "First-Order Predicate Logic: Universal and Existential Quantifiers & Negations",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "First Order Logic Quantifiers and Translations for GATE",
      type: "youtube",
      creator: "Amit Khurana",
      url: "https://www.youtube.com/results?search_query=first+order+predicate+logic+gate+amit+khurana",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dm-3",
    title: "Sets, Relations, Equivalence Relations & Equivalence Classes",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Equivalence Relations and Reflexive Symmetric Transitive Closures",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=equivalence+relations+gate+smashers",
      badge: "Concept Lecture",
    },
  },
  {
    id: "gate-dm-4",
    title: "Partially Ordered Sets (Posets), Hasse Diagrams & Lattices",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Posets Hasse Diagram and Lattices Explained",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=posets+hasse+diagram+lattices+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dm-5",
    title: "Functions: Injective (One-to-One), Surjective (Onto), Bijective & Pigeonhole Principle",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Counting Functions and Pigeonhole Principle Solved Problems",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=pigeonhole+principle+functions+gate+smashers",
      badge: "Solved Examples",
    },
  },
  {
    id: "gate-dm-6",
    title: "Combinatorics: Permutations, Combinations & Principle of Inclusion-Exclusion",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Inclusion Exclusion Principle and Combinatorics for GATE",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=inclusion+exclusion+principle+gate+smashers",
      badge: "Method & Shortcuts",
    },
  },
  {
    id: "gate-dm-7",
    title: "Generating Functions & Solving Homogeneous and Non-Homogeneous Recurrence Relations",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "Theory · 3 Marks",
    resource: {
      title: "Solving Recurrence Relations using Characteristic Equations",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=solving+recurrence+relations+discrete+maths+gate",
      badge: "Formula & Steps",
    },
  },
  {
    id: "gate-dm-8",
    title: "Graph Theory: Paths, Cycles, Handshaking Lemma & Degree Sequences",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "Core Fundamental · 2 Marks",
    resource: {
      title: "Handshaking Lemma and Graph Theory Basics",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=handshaking+lemma+graph+theory+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-dm-9",
    title: "Eulerian Graphs vs Hamiltonian Graphs & Bipartite Graph Properties",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Euler Path Euler Circuit and Hamiltonian Cycle Differences",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=euler+graph+hamiltonian+graph+gate+smashers",
      badge: "Core Differences",
    },
  },
  {
    id: "gate-dm-10",
    title: "Graph Coloring, Chromatic Number & Planar Graphs (Euler's Formula: V - E + F = 2)",
    categoryId: "dm",
    categoryName: "Discrete Mathematics",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Planar Graphs Euler Formula and Chromatic Number",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=planar+graphs+chromatic+number+gate+smashers",
      badge: "High Yield Video",
    },
  },

  // ── 9. DIGITAL LOGIC & COMPUTER ORGANIZATION (11 Subtasks) ─────
  {
    id: "gate-coa-1",
    title: "Boolean Algebra, Logic Gates & Karnaugh Map (K-Map) Simplification with Don't Cares",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "K-Map Simplification 4 Variables with Don't Care Conditions",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=k+map+simplification+gate+smashers",
      badge: "YouTube Lecture",
    },
  },
  {
    id: "gate-coa-2",
    title: "Combinational Circuits: Multiplexers (MUX), Demux, Decoders & Encoders",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Implementing Boolean Functions using Multiplexers",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=multiplexer+boolean+function+gate+smashers",
      badge: "High Yield Video",
    },
  },
  {
    id: "gate-coa-3",
    title: "Sequential Circuits: SR, JK, D, T Flip-Flops, Conversion & Characteristic Tables",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "High Yield · 3 Marks",
    resource: {
      title: "Flip Flop Conversion and Excitation Tables Made Easy",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=flip+flop+conversion+excitation+table+gate+smashers",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-coa-4",
    title: "Synchronous and Asynchronous Counters Design & Modulo-N Counting",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "Synchronous Counter Design and Sequence Detection",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=synchronous+counter+design+gate",
      badge: "Design Guide",
    },
  },
  {
    id: "gate-coa-5",
    title: "Machine Instructions & Addressing Modes (Immediate, Direct, Indirect, Indexed, PC-Relative)",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Addressing Modes Explained with Assembly Instruction Examples",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=addressing+modes+computer+organization+gate+smashers",
      badge: "Essential Video",
    },
  },
  {
    id: "gate-coa-6",
    title: "Instruction Pipelining: Stages, Pipeline Throughput, Speedup & Efficiency",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Instruction Pipelining Formulas and Speedup Calculation",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=pipelining+speedup+efficiency+gate+smashers",
      badge: "High Yield Video",
    },
  },
  {
    id: "gate-coa-7",
    title: "Pipeline Hazards: Structural, Data Hazards (RAW, WAR, WAW) & Control Hazards",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Core Fundamental · 3 Marks",
    resource: {
      title: "Pipeline Hazards and Forwarding Stall Calculations",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=pipeline+hazards+data+hazard+gate",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-coa-8",
    title: "Cache Memory Organization: Direct Mapping, Fully Associative & Set-Associative Mapping",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "High Yield · 4 Marks",
    resource: {
      title: "Cache Memory Mapping Tag Index Block Offset Formulas",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=cache+memory+mapping+gate+smashers",
      badge: "Top Masterclass",
    },
  },
  {
    id: "gate-coa-9",
    title: "Cache Hit Ratio, Miss Penalties & Average Memory Access Time (AMAT) with Multi-level Cache",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Numerical · 3 Marks",
    resource: {
      title: "Average Memory Access Time AMAT Solved Problems",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=average+memory+access+time+amat+gate+smashers",
      badge: "Solved Problems",
    },
  },
  {
    id: "gate-coa-10",
    title: "Cache Write Policies: Write-Through vs Write-Back & Write-Allocate vs No-Write-Allocate",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Concept · 2 Marks",
    resource: {
      title: "Cache Write Policies Write Through Write Back Explained",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=cache+write+policies+gate",
      badge: "Concept Video",
    },
  },
  {
    id: "gate-coa-11",
    title: "Input/Output Interfacing: Programmed I/O, Interrupt-Driven I/O & DMA Data Transfer",
    categoryId: "coa",
    categoryName: "Digital Logic & Computer Org",
    status: "pending",
    weight: "Core Theory · 2 Marks",
    resource: {
      title: "DMA Controller Operation & Cycle Stealing Mode",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=dma+controller+cycle+stealing+gate+smashers",
      badge: "Video Tutorial",
    },
  },

  // ── 10. GENERAL APTITUDE & PYQS (10 Subtasks) ───────────────────
  {
    id: "gate-apt-1",
    title: "Quantitative Aptitude: Percentages, Profit & Loss, Ratios & Mixtures",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Quantitative Aptitude Formulas and Quick Shortcuts",
      type: "youtube",
      creator: "CareerRide",
      url: "https://www.youtube.com/results?search_query=quantitative+aptitude+percentages+ratios+careerride",
      badge: "Aptitude Tricks",
    },
  },
  {
    id: "gate-apt-2",
    title: "Time & Work, Pipes & Cisterns, Speed, Time & Distance Problems",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Time and Work Speed Distance Solved Questions",
      type: "youtube",
      creator: "Feel Free to Learn",
      url: "https://www.youtube.com/results?search_query=time+and+work+speed+distance+gate+aptitude",
      badge: "Shortcut Methods",
    },
  },
  {
    id: "gate-apt-3",
    title: "Analytical Reasoning: Syllogisms, Blood Relations, Seating Arrangements & Coding-Decoding",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Scoring Topic · 3 Marks",
    resource: {
      title: "Syllogism and Blood Relations for GATE Aptitude",
      type: "youtube",
      creator: "CareerRide",
      url: "https://www.youtube.com/results?search_query=syllogism+blood+relations+gate+aptitude",
      badge: "Video Tutorial",
    },
  },
  {
    id: "gate-apt-4",
    title: "Verbal Ability: Grammar Rules, Error Spotting, Sentence Completion & Critical Reasoning",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Scoring Topic · 3 Marks",
    resource: {
      title: "Verbal Ability for GATE Exam Crash Course",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=verbal+ability+gate+smashers",
      badge: "Crash Course",
    },
  },
  {
    id: "gate-apt-5",
    title: "Spatial Aptitude: Paper Folding, Reflection, 2D/3D Transformations & Rotations",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Scoring Topic · 2 Marks",
    resource: {
      title: "Spatial Aptitude for GATE Complete Video",
      type: "youtube",
      creator: "Unacademy Computer Science",
      url: "https://www.youtube.com/results?search_query=spatial+aptitude+gate+cs",
      badge: "Visual Guide",
    },
  },
  {
    id: "gate-pyq-1",
    title: "Solve Official GATE 2025 CS Question Paper with In-depth Review",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Full Paper Simulation · 100 Marks",
    resource: {
      title: "GATE 2025 CS Solutions & Complete Paper Discussion",
      type: "youtube",
      creator: "Gate Smashers",
      url: "https://www.youtube.com/results?search_query=gate+2025+cs+paper+solution+gate+smashers",
      badge: "Solved Paper",
    },
  },
  {
    id: "gate-pyq-2",
    title: "Solve Official GATE 2024 CS Question Paper with Detailed Solutions",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Full Paper Simulation · 100 Marks",
    resource: {
      title: "GATE 2024 CS Paper Solutions by Top Faculty",
      type: "youtube",
      creator: "Knowledge Gate",
      url: "https://www.youtube.com/results?search_query=gate+2024+cs+paper+solutions",
      badge: "Solved Paper",
    },
  },
  {
    id: "gate-pyq-3",
    title: "Solve Official GATE 2022 & 2023 CS Question Papers",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "High Yield PYQ · 100 Marks",
    resource: {
      title: "GATE 2023 CS Complete Paper Solution Discussion",
      type: "youtube",
      creator: "Amit Khurana",
      url: "https://www.youtube.com/results?search_query=gate+2023+cs+paper+solution+amit+khurana",
      badge: "Video Solution",
    },
  },
  {
    id: "gate-mock-1",
    title: "Full-Length 3-Hour Timed Mock Exam 1 (65 Questions, Virtual Calculator, Negative Marking)",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Full Mock Test · 100 Marks",
    resource: {
      title: "GATE Overflow Official Free Test Series & Mock Exams",
      type: "practice",
      creator: "GATE Overflow",
      url: "https://gateoverflow.in/",
      badge: "Practice Mock",
    },
  },
  {
    id: "gate-mock-2",
    title: "Full-Length 3-Hour Timed Mock Exam 2 & Final Weak Area Revision Sprint",
    categoryId: "mocks",
    categoryName: "General Aptitude & PYQs",
    status: "pending",
    weight: "Grand Mock Simulation · 100 Marks",
    resource: {
      title: "GeeksforGeeks GATE CS Mock Tests & Subject Tests",
      type: "practice",
      creator: "GeeksforGeeks",
      url: "https://www.geeksforgeeks.org/gate-cs-notes-gq/",
      badge: "Grand Revision",
    },
  },
];

export const GATE_SUBTASKS = GATE_100_SUBTASKS;
