"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge, Btn, Icon, PageHead, RiskBadge, StatusDot, Empty } from "./ui";

export type TaskView = {
  id: string; title: string; description: string | null; priority: string | null;
  deadline: string | null; status: string | null; source: string | null;
  points: number | null; goalTitle: string | null;
};

const STATUSES = ["inbox", "planned", "in_progress", "waiting", "blocked", "completed", "cancelled"] as const;
const LABEL: Record<string, string> = { inbox: "Inbox", planned: "Planned", in_progress: "In Progress", waiting: "Waiting", blocked: "Blocked", completed: "Completed", cancelled: "Cancelled" };
const TONE: Record<string, string> = { inbox: "muted", planned: "info", in_progress: "accent", waiting: "warn", blocked: "danger", completed: "ok", cancelled: "muted" };
const NEXT: Record<string, string> = { inbox: "planned", planned: "in_progress", in_progress: "waiting", waiting: "in_progress", blocked: "planned", completed: "planned", cancelled: "inbox" };

export default function TasksBoard({ tasks }: { tasks: TaskView[] }) {
  const [filter, setFilter] = useState<string>("all");
  const [busyId, setBusyId] = useState<string | null>(null);
  const router = useRouter();

  const act = async (id: string, status: string) => {
    setBusyId(id);
    try {
      await fetch("/api/mutate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "task.status", id, status }) });
      router.refresh();
    } finally { setBusyId(null); }
  };

  const shown = tasks.filter((t) => filter === "all" ? t.status !== "completed" || filter === "all" : t.status === filter);
  const open = tasks.filter((t) => !["completed", "cancelled"].includes(t.status ?? ""));

  return (
    <div>
      <PageHead
        title="Tasks"
        sub={`${open.length} open · generated by you and the agent — every agent-created task is policy-checked and audited`}
        right={<Btn size="sm" variant="ghost" onClick={() => router.push("/")}><Icon name="plus" size={12} /> Ask Orbit to create one</Btn>}
      />
      <div className="mb-4 flex flex-wrap gap-1.5">
        {["all", "inbox", "planned", "in_progress", "waiting", "blocked", "completed"].map((f) => (
          <button key={f} onClick={() => setFilter(f)} className={`rounded-lg px-2.5 py-1 text-[12px] transition-colors ${filter === f ? "bg-accent-soft text-accent" : "text-muted hover:bg-white/5 hover:text-ink"}`}>
            {f === "all" ? `All open (${open.length})` : LABEL[f]}
          </button>
        ))}
      </div>

      {shown.length === 0 ? (
        <Empty text="Nothing here. Tell Orbit a goal in the command center and tasks will appear." />
      ) : (
        <div className="space-y-2">
          {shown.map((t) => (
            <div key={t.id} className="fade-up flex items-center gap-3 rounded-xl border border-line bg-surface px-3.5 py-3">
              <button
                onClick={() => void act(t.id, t.status === "completed" ? "planned" : "completed")}
                disabled={busyId === t.id}
                className={`grid h-5 w-5 shrink-0 place-items-center rounded-md border transition ${t.status === "completed" ? "border-ok bg-ok/20 text-ok" : "border-line text-transparent hover:border-accent"}`}
                title={t.status === "completed" ? "Reopen" : "Complete"}
              >
                <Icon name="check" size={12} />
              </button>
              <div className="min-w-0 flex-1">
                <div className={`truncate text-[13.5px] ${t.status === "completed" ? "text-faint line-through" : "text-ink"}`}>{t.title}</div>
                {t.description && <div className="mt-0.5 truncate text-[11.5px] text-faint">{t.description}</div>}
              </div>
              {typeof t.points === "number" && <Badge tone="accent">+{t.points} pts</Badge>}
              {t.goalTitle && <Badge tone="muted" className="hidden md:inline-flex">{t.goalTitle}</Badge>}
              <span className="hidden text-[11px] text-faint sm:block">{t.source}</span>
              {t.deadline && (
                <span className="shrink-0 font-mono text-[11px] text-muted flex items-center gap-1">
                  <Icon name="calendar" size={10} className="text-faint" />
                  {(() => {
                    const d = new Date(t.deadline);
                    const isToday = d.toDateString() === new Date().toDateString();
                    const dateStr = isToday ? "Today" : d.toLocaleDateString("en-IN", { day: "numeric", month: "short" });
                    const timeStr = d.toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" }).replace(" ", "").toLowerCase();
                    return `${dateStr} · ${timeStr}`;
                  })()}
                </span>
              )}
              <button onClick={() => void act(t.id, NEXT[t.status ?? "inbox"])} disabled={busyId === t.id} className={`shrink-0 rounded-md border px-2 py-0.5 text-[11px] transition hover:brightness-110 ${`border-transparent bg-white/5 text-muted`}`}>
                <Badge tone={TONE[t.status ?? "inbox"]}>{LABEL[t.status ?? "inbox"]}</Badge>
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
